- name: Install Pip
  become: "{{ python_should_become }}"
  package:
    name: python3-pip
    state: present
    use: "{{ python_package_manager }}"
  when: python_install_pip_separately

- name: Install Python packages
  pip:
    name: "{{ python_packages }}"
    state: present
    extra_args: "--user"
    executable: "{{ which_pip }}"
