- name: Install zsh
  become: "{{ zsh_should_become }}"
  package:
    name: zsh
    state: present
    use: "{{ zsh_package_manager }}"

- name: Set zsh as the default shell
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    shell: "{{ zsh_bin_location }}"

- name: Ensure zsh completions directory exists
  file:
    path: "{{ zsh_completions_dir }}"
    state: directory

- name: Ensure zsh plugins directory exists
  file:
    path: "{{ zsh_plugins_dir }}"
    state: directory

- name: Download plugins
  git:
    repo: "{{ item.url }}"
    dest: "{{ zsh_plugins_dir }}/{{ item.name }}"
    clone: yes
    force: yes
  with_items: "{{ zsh_plugins }}"

- name: Clone base16-shell repo
  git:
    repo: "https://github.com/chriskempson/base16-shell.git"
    dest: "{{ config_root }}/base16-shell"
    clone: yes
    force: yes

- name: Copy files
  copy:
    src: files/
    dest: "{{ ansible_env.HOME }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ zsh_owner_group }}"

- name: Copy templates
  template:
    src: "{{ item }}.j2"
    dest: "{{ ansible_env.HOME }}/{{ item }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ zsh_owner_group }}"
  with_items:
    - .zshrc
    - .zsh_prompt
    - .zsh_aliases

- name: Add .hushlogin
  file:
    path: "{{ ansible_env.HOME }}/.hushlogin"
    state: touch
  when: zsh_add_hushlogin
