- name: Install zsh
  become: yes
  package:
    name: zsh
    state: present

- name: Set zsh as the default shell
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/zsh

- name: Ensure main dotfiles directory exists
  file:
    path: "{{ ansible_env.HOME }}/.dotfiles"
    state: directory

- name: Ensure zsh dotfiles directory exists
  file:
    path: "{{ zsh_dotfiles_root }}"
    state: directory

- name: Download plugins
  git:
    repo: "{{ item.url }}"
    dest: "{{ zsh_dotfiles_root }}/{{ item.name }}"
    clone: yes
    force: yes
  with_items: "{{ zsh_plugins }}"

- name: Clone base16-shell repo
  git:
    repo: "https://github.com/chriskempson/base16-shell.git"
    dest: "{{ config_root }}/base16-shell"
    clone: yes
    force: yes

- name: Ensure completions directory exists
  file:
    path: "{{ zsh_dotfiles_root }}/completions"
    state: directory

- name: Copy files
  copy:
    src: files/
    dest: "{{ zsh_dotfiles_root }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"

- name: Copy templates
  template:
    src: "{{ item }}.j2"
    dest: "{{ zsh_dotfiles_root }}/{{ item }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  with_items:
    - .zshrc
    - prompt
    - aliases

- name: Create symbolic links
  file:
    src: "{{ zsh_dotfiles_root }}/{{ item }}"
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: link
    force: yes
  with_items:
    - .zshrc
    - .zshenv
    - .zprofile

- name: Reminder to set the color scheme
  command: echo base16_ocean
