- name: Install neovim
  become: "{{ neovim_should_become }}"
  package:
    name: neovim
    state: present
    use: "{{ neovim_package_manager }}"

- name: Install neovim Python package
  pip:
    name: neovim
    state: latest
    extra_args: --user

- name: Detect dein installation
  command: test -d "{{ ansible_env.HOME }}/.config/nvim/bundle"
  register: dein_already_installed
  failed_when: dein_already_installed.stderr != ""

- block:
  - name: Download dein installer
    get_url:
      url: "https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh"
      dest: "/tmp/dein_installer.sh"
  - name: Run dein installer
    command: bash /tmp/dein_installer.sh "{{ neovim_config_root }}/bundle"
  - name: Remove dein installer
    file:
      path: /tmp/dein_installer.sh
      state: absent
  when: dein_already_installed.rc == 1

- name: Copy init.vim
  copy:
    src: init.vim
    dest: "{{ neovim_config_root }}/init.vim"
    owner: "{{ ansible_user_id }}"
    group: "{{ neovim_owner_group }}"
